version: '3.8'

services:
  flask-app:
    build: .
    container_name: flask_container
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/user_db
    volumes:
      - .:/app
    restart: always

  mongodb:
    image: mongo:6.0
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
